SELECT APS.USERNAME, C.NAME ,FC.QUESTION ,FC.ANSWER 
FROM ASSOCIATE.STUDY_SET_CARD SSC, CATEGORY c 
INNER JOIN STUDY_SET SS
 ON SS.STUDY_SET_ID=SSC.STUDY_SET_ID
  INNER JOIN APP_USER APS
   ON AS.USER_ID = SS.OWNER_ID 
  INNER JOIN CATEGORY C
   ON AS C.CATEGORY_ID=FC.CATEGORY_ID 
INNER JOIN FLASHCARD FC
 ON FC.FLASHCARD_ID = SSC.FLASHCARD_ID
WHERE STUDY_SET.STUDY_SET_ID = 4 ;
